---
title: El modo de espera en frío genera el error "El registro de DataStoreException no existe"
description: Descripción
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: AEM KCS,, espera pasiva, DataStoreException, Adobe Experience Manager, el registro no existe, error, advertencia, advertencia
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Jim Menn
article-created-date: 9/28/2022 2:23:47 PM
article-published-by: Jim Menn
article-published-date: 9/28/2022 5:41:23 PM
version-number: 3
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=5e521024-393f-ed11-9db1-0022480866ad
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: 4702b69f883128bf305ec64f012ef01903f3f582
workflow-type: tm+mt
source-wordcount: '231'
ht-degree: 1%

---

# El modo de espera en frío genera el error &quot;El registro de DataStoreException no existe&quot;

## Descripción


<b>Entorno</b>
Adobe Experience Manager

<b>Problema</b>
El modo de espera en frío con el almacén de datos de archivos dedicado emite una advertencia sobre la falta de un ID de blob similar al error aquí:


```
*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522

java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist

    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3

...

Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist

    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```


<b>Causa</b>
Esto es solo una advertencia, no un error.

Se debe a que el almacén de datos de archivos no tiene forma de verificar si un binario existe localmente, excepto intentando cargar el ID del blob.
Si se carga el ID, los registros no muestran esta advertencia.
Sin embargo, si no se encuentra, el modo de espera sabe que tiene que sincronizarlo, por lo que ve este tipo de advertencia en los registros.


## Resolución


<b>Solución</b>
Esto funciona según lo diseñado y no indica un problema con el almacén de datos de archivos.

Para confirmar que en realidad no falta el ID del blob, siga estos pasos:

1. Por ejemplo, tome su ID del blob de muestra que se muestra como ausente en los registros (por ejemplo: `cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`).
2. Para este ID de blob en este ejemplo, la dirección del sistema de archivos debe ser: `ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
3. Busque el sistema de archivos en la instancia de espera y compruebe si el archivo con nombre está presente en el almacén de datos de archivos.
4. En `/repository/datastore`, use el `list` (Por ejemplo: `ls -ald`), comando: `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
5. Debería poder ver el archivo y confirmar que en realidad no falta el ID del blob.
